const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Tilemap.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.random,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Tilemap.Cnds.CompareOpacity,
		C3.Plugins.Tilemap.Cnds.CompareY,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Variables: 0},
	{snif: 0},
	{doublejump: 0},
	{Platform: 0},
	{Tween: 0},
	{player: 0},
	{Solid: 0},
	{col: 0},
	{win: 0},
	{defeat: 0},
	{ScrollTo: 0},
	{gamemanager: 0},
	{player_spr: 0},
	{btnRight: 0},
	{btnLeft: 0},
	{btnUp: 0},
	{Timer: 0},
	{tree: 0},
	{rescue: 0},
	{hidden: 0},
	{pet: 0},
	{snif_masc: 0},
	{Backgroud: 0},
	{Backgroud2: 0},
	{Backgroud3: 0},
	{Backgroud4: 0},
	{Tilemap: 0},
	{bgWin: 0},
	{transition: 0},
	{Sine: 0},
	{tap_to_continue: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnSound: 0},
	{name: 0},
	{txtUI: 0},
	{btnArrowRight: 0},
	{nHoja: 0},
	{btnArrowLeft: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{txtBtnNivel: 0},
	{selector_manager: 0},
	{Anchor: 0},
	{Game_Tittle: 0},
	{btnPlay: 0},
	{Water: 0},
	{bg_ui: 0},
	{menumanager: 0},
	{tutorial: 0},
	{in: 0},
	{arrow: 0},
	{msj: 0},
	{signinfo: 0},
	{sign_tutorial: 0},
	{out: 0},
	{Fade: 0},
	{Fade2: 0},
	{tilde_level: 0},
	{goGame: 0},
	{taptoplay: 0},
	{deco: 0},
	{btnDown: 0},
	{bridge: 0},
	{secretpath: 0},
	{pathup: 0},
	{startY: 0},
	{endY: 0},
	{TilemapHiden: 0},
	{springchamp: 0},
	{bgmasc: 0},
	{Pets: 0},
	{Buttons: 0},
	{ButtonsMobile: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0},
	{LEVEL: 0},
	{totStars: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{double_jump: 0},
	{SOUNDVOLUME: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Variables: class extends self.IArrayInstance {},
	player: class extends self.ISpriteInstance {},
	col: class extends self.ISpriteInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	player_spr: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnUp: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	pet: class extends self.ISpriteInstance {},
	snif_masc: class extends self.ISpriteInstance {},
	Backgroud: class extends self.ISpriteInstance {},
	Backgroud2: class extends self.ISpriteInstance {},
	Backgroud3: class extends self.ISpriteInstance {},
	Backgroud4: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	bgWin: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	tap_to_continue: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	nHoja: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	selector_manager: class extends self.ISpriteInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	bg_ui: class extends self.I9PatchInstance {},
	menumanager: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	signinfo: class extends self.ISpriteInstance {},
	sign_tutorial: class extends self.ISpriteInstance {},
	tilde_level: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	deco: class extends self.ISpriteInstance {},
	btnDown: class extends self.ISpriteInstance {},
	TilemapHiden: class extends self.ITilemapInstance {},
	springchamp: class extends self.ISpriteInstance {},
	bgmasc: class extends self.ISpriteInstance {},
	Pets: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	ButtonsMobile: class extends self.ISpriteInstance {}
}